### ISSUE TITLE
The output of a program is not checked to be a regular file

### ISSUE THREAD

**Issue by rqu** [ReCodEx/worker#31]
Where a regular file is expected as the output of the evaluated program, a symlink usually goes unnoticed.

**Steps to reproduce:**

Submit the following program to a C or C++ exercise judged by the token judge according to its stdout. External commands are not really needed; this could be implemented using only C.

```c
#include <stdlib.h>

int main(int argc, char** argv) {
	system("ln -sf expected.out *.stdout");
	return 0;
}
```

**Expected behavior:** The solution should be rejected.

**Observed behavior:** The solution is accepted.

I am not sure what component should be responsible for filtering out symlinks (should each and every judge check its input?).

Note: this is unrelated to #29, which is about directory symlinks. Symlinks to files are always copied unresolved.

**Comment by krulis-martin** [comment]
Agreed, this might be a problem. We will probably prevent copying all symlinks back from sandbox, since they are bit of a nuisance anyway.

**Comment by rqu** [comment]
OK. When you are implementing this restriction, you may also want to disallow hard links. They are not as dangerous, but when copied, each link is copied as a separate file, so the target directory may be larger than the source. (I wanted to try this, but ran into #32.)

The number of hard links is returned by `lstat` (along with the file type, which we are querying anyway). I do not see that in `boost::filesystem::file_status`, although there is `hard_link_count(const path&)`.
